[package]
name = "openapi-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"

[[bin]]
name = "openapi-rust"
path = "src/main.rs"
